nodeLinker: "pnp"
packageExtensions:
  html-webpack-plugin@*:
    dependencies:
      loader-utils: ^2.0.0
  webpack-manifest-plugin@*:
    dependencies:
      webpack: ^5.47.0

yarnPath: .yarn/releases/yarn-3.0.0.cjs
